version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./server/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react
    networks:
      - app-network

  react:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge